### PR TITLE
Separate into internal object-store crate

### LINKED ISSUE #3: Expose Python interface for other Rust applications?
👋 I'm building [a Rust-Python library](https://github.com/geoarrow/geoarrow-rs/tree/main/python) that depends on object-store. It would be nice to reuse existing Python APIs that are built on object-store, i.e. your crate. From [this comment](https://github.com/PyO3/pyo3/discussions/2340#discussioncomment-2646525) and [this comment](https://github.com/pola-rs/polars/issues/1325#issuecomment-1208607232), I think the primary way to enable this is to split into two crates: an `rlib` crate that contains everything but the actual `#[pymodule]` definition and a `cdylib` crate that is the actual Python module. The former would be able to be depended on by multiple pyo3 libraries, while the latter would be your existing Python package.

I know this is an increase in complexity, but are you interested in a PR for this?

### PR DESCRIPTION
**Pull request by kylebarron**
Considerations:

- Most dependencies and rust code are moved to the internal `object-store-internal` crate. Only the actual `#[pymodule]` is in the existing python crate.
- The internal `rlib` crate would be published to crates.io, and so naming and struct visibility should be considered. I.e. I'd recommend `object-store-python` as the name of the internal crate, as that would be descriptive for people to see on crates.io.
- I also haven't given thought yet/tried to how a third party will actually use `object-store-internal`. The hope is that it will be possible for a third party rust-python binding 

Closes https://github.com/roeap/object-store-python/issues/3

### CODE REVIEW

**Comment by roeap** [comment]
Thanks for putting this up @kylebarron. 

Before merging this, I'd just like to see if @tustvold has an opinion on this - since providing python integrations behind a feature flag is not uncommon in the arrow-ecosystem at large, maybe it may even make sense to completely upstream this to object_store behind a feature gate?

Not sure if this would even be a good idea, especially the Arrow file system stuff, but just making sure...

**Comment by kylebarron** [comment]
arrow-rs implements conversions with _existing_ Python objects (e.g. importing from and exporting to pyarrow arrays), rather than defining any new Python objects itself. Thus I'd have guessed this would be out of scope for object-store, but similarly interested in tustvold's thoughts.

**Comment by tustvold** [comment]
I think having python bindings for the object_store crate would be pretty compelling, although historically the sticking point has been the lack of a good story for async across the FFI boundary. I am not sure if this has improved, I see this crate is using block_on which is perhaps unfortunate, and so my feelings on the matter would likely depend on whether this state of play has improved recently.

**Comment by kylebarron** [comment]
In https://github.com/roeap/object-store-python/pull/6 I implemented async bindings to Python using [pyo3-asyncio](https://github.com/awestlake87/pyo3-asyncio), which is the best thing available today. It looks like the next release of pyo3 will have better built-in support for async. See https://github.com/PyO3/pyo3/pull/3540 and https://github.com/PyO3/pyo3/issues/1632

**Comment by roeap** [comment]
@tustvold @kylebarron - maybe we just start here, and see where this ends up. If we are happy then upstream it..

**Comment by roeap** [comment]
@kylebarron thanks for doing this and sorry for the delay, more keeps me from doing fun stuff :D.

**Pull request merged**
